# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve -l -H localhost`. If you change this file, please restart the
# server process.

# Basic Site Settings
locale: "en-US"
title: "SOURAV DAS - Research Portfolio"
title_separator: "-"
name: "Sourav Das"
description: >-
  Ph.D. candidate in Mechanical Engineering with 4 years of industry experience in design engineering and a deep research focus on Li-ion battery degradation, diagnostics, and digital twin modeling. Proven ability to lead complex projects, from industrial pipeline design for global EPC firms to pioneering novel battery analysis workflows resulting in first-author publications and an R&D 100 Award.
url: "https://souravds1.github.io" 
repository: "souravds1/souravds1.github.io" 

# Author Settings
author:
  name: "Sourav Das"
  avatar: "profile.png"
  pronouns: "He/him"
  bio: "Ph.D. Researcher at Iowa State University focusing on Energy Storage, Digital Twins, and Machine Learning."
  location: "Ames, IA"
  employer: "Iowa State University"
  email: "sourav1@iastate.edu"
  
  # Social and Academic Links
  linkedin: "souravds1"
  github: "souravds1"
  googlescholar: "https://scholar.google.com/citations?user=PS_CX0AAAAAJ"
  orcid: "https://orcid.org/0000-0001-6997-1698"

# Publication Category - The following the list of publication categories and their headings
publication_category:
  books:
    title: 'Books'
  manuscripts:
    title: 'Journal Articles'    
  conferences:
    title: 'Conference Papers'

# Site Settings
teaser: # filename of teaser fallback teaser image placed in /images/, .e.g. "500x300.png"
breadcrumbs: false # true, false (default)
words_per_minute: 160
future: true
read_more: "disabled" # if enabled, adds "Read more" links to excerpts
talkmap_link: false      #change to true to add link to talkmap on talks page
comments:
  provider: # false (default), "disqus", "discourse", "facebook", "google-plus", "staticman", "custom"
  disqus:
    shortname:
  discourse:
    server: # https://meta.discourse.org/t/embedding-discourse-comments-via-javascript/31963 , e.g.: meta.discourse.org
  facebook:
    appid:
    num_posts: # 5 (default)
    colorscheme: # "light" (default), "dark"

# Analytics
analytics:
  provider: "false" # false (default), "google", "google-universal", "google-analytics-4", "custom"
  google:
    tracking_id:

# Reading Files
include:
  - .htaccess
  - _pages
  - files
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .github
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/_main.js
  - assets/js/plugins
  - assets/js/vendor
  - CHANGELOG
  - Capfile
  - config
  - Dockerfile
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - local
  - log
  - node_modules
  - package.json*
  - Rakefile
  - README
  - tmp
  - vendor
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"


# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false


# Collections
collections:
  teaching:
    output: true
    permalink: /:collection/:path/
  publications:
    output: true
    permalink: /:collection/:path/
  portfolio:
    output: true
    permalink: /:collection/:path/
  talks:
    output: true
    permalink: /:collection/:path/


# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  # _teaching
  - scope:
      path: ""
      type: teaching
    values:
      layout: single
      author_profile: true
      share: true
      comments: true
  # _publications
  - scope:
      path: ""
      type: publications
    values:
      layout: single
      author_profile: true
      share: true
      comments: true
  # _portfolio
  - scope:
      path: ""
      type: portfolio
    values:
      layout: single
      author_profile: true
      share: true
      comment: true
  # _talks
  - scope:
      path: ""
      type: talks
    values:
      layout: talk
      author_profile: true
      share: true


# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed


# Outputting
permalink: /:categories/:title/
timezone: Etc/UTC


# Plugins
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji
